;adb.constants.au3

#include-once
Global Const $INSTALL_SUCCEEDED = 1
Global Const $INSTALL_FAILED_ALREADY_EXISTS = -1
Global Const $INSTALL_FAILED_INVALID_APK = -2
Global Const $INSTALL_FAILED_INVALID_URI = -3
Global Const $INSTALL_FAILED_INSUFFICIENT_STORAGE = -4
Global Const $INSTALL_FAILED_DUPLICATE_PACKAGE = -5
Global Const $INSTALL_FAILED_NO_SHARED_USER = -6
Global Const $INSTALL_FAILED_UPDATE_INCOMPATIBLE = -7
Global Const $INSTALL_FAILED_SHARED_USER_INCOMPATIBLE = -8
Global Const $INSTALL_FAILED_MISSING_SHARED_LIBRARY = -9
Global Const $INSTALL_FAILED_REPLACE_COULDNT_DELETE = -10
Global Const $INSTALL_FAILED_DEXOPT = -11
Global Const $INSTALL_FAILED_OLDER_SDK = -12
Global Const $INSTALL_FAILED_CONFLICTING_PROVIDER = -13
Global Const $INSTALL_FAILED_NEWER_SDK = -14
Global Const $INSTALL_FAILED_TEST_ONLY = -15
Global Const $INSTALL_FAILED_CPU_ABI_INCOMPATIBLE = -16
Global Const $INSTALL_FAILED_MISSING_FEATURE = -17
Global Const $INSTALL_FAILED_CONTAINER_ERROR = -18
Global Const $INSTALL_FAILED_INVALID_INSTALL_LOCATION = -19
Global Const $INSTALL_FAILED_MEDIA_UNAVAILABLE = -20
Global Const $INSTALL_FAILED_VERIFICATION_TIMEOUT = -21
Global Const $INSTALL_FAILED_VERIFICATION_FAILURE = -22
Global Const $INSTALL_FAILED_PACKAGE_CHANGED = -23
Global Const $INSTALL_FAILED_UID_CHANGED = -24
Global Const $INSTALL_FAILED_VERSION_DOWNGRADE = -25
Global Const $INSTALL_FAILED_INTERNAL_ERROR = -110
Global Const $INSTALL_FAILED_USER_RESTRICTED = -111